server:
  port:

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot:
    token:
    webhook-url: